/* This file is automatically generated with "make proto". DO NOT EDIT */

uint32 get_checksum1(char *buf,int len);
void get_checksum2(char *buf,int len,char *sum);
void file_checksum(char *fname,char *sum,off_t size);
struct file_list *send_file_list(int f,int recurse,int argc,char *argv[]);
struct file_list *recv_file_list(int f);
int do_cmd(char *cmd,char *machine,char *user,char *path,int *f_in,int *f_out);
void do_server_sender(int argc,char *argv[]);
void do_server_recv(int argc,char *argv[]);
void usage(void);
int main(int argc,char *argv[]);
void match_sums(int f,struct sum_struct *s,char *buf,off_t len);
void recv_generator(char *fname,struct file_list *flist,int i,int f_out);
int recv_files(int f_in,struct file_list *flist,char *local_name);
off_t send_files(struct file_list *flist,int f_out,int f_in);
int write_total(void);
int read_total(void);
void write_int(int f,int x);
void write_buf(int f,char *buf,int len);
void write_flush(int f);
int readfd(int fd,char *buffer,int N);
int read_int(int f);
void read_buf(int f,char *buf,int len);
char *map_file(int fd,off_t len);
void unmap_file(char *buf,off_t len);
int piped_child(char **command,int *f_in,int *f_out);
void out_of_memory(char *str);
